-- =============================================================================
-- WCSAA Scoring App — Supabase PostgreSQL Schema
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- =============================================================================

-- Enable UUID extension (already enabled in Supabase by default)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- TABLE: seasons
-- One row per league season (e.g. "2025-26", "2026-27")
-- Only one row should have is_active = TRUE at a time.
-- =============================================================================
CREATE TABLE IF NOT EXISTS seasons (
    season_id   TEXT PRIMARY KEY,          -- e.g. "2025-26"
    is_active   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- TABLE: anglers
-- One row per angler per season. Composite PK allows same WP number across seasons.
-- =============================================================================
CREATE TABLE IF NOT EXISTS anglers (
    wp_no           TEXT NOT NULL,
    season_id       TEXT NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
    sasaa_no        TEXT NOT NULL DEFAULT '',
    first_name      TEXT NOT NULL DEFAULT '',
    surname         TEXT NOT NULL DEFAULT '',
    club            TEXT NOT NULL DEFAULT '',
    sub_team        TEXT NOT NULL DEFAULT '',
    league_division TEXT NOT NULL DEFAULT '',
    league_code     TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (wp_no, season_id)
);

-- =============================================================================
-- TABLE: competitions
-- One row per competition per season.
-- =============================================================================
CREATE TABLE IF NOT EXISTS competitions (
    comp_id     TEXT NOT NULL,
    season_id   TEXT NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
    date        TEXT NOT NULL DEFAULT '',
    venue       TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (comp_id, season_id)
);

-- =============================================================================
-- TABLE: catches_raw
-- Raw catch entries — one row per catch.
-- No natural composite PK; serial ID used. Season scoped via season_id.
-- =============================================================================
CREATE TABLE IF NOT EXISTS catches_raw (
    id          BIGSERIAL PRIMARY KEY,
    season_id   TEXT NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
    comp_id     TEXT NOT NULL DEFAULT '',
    wp_no       TEXT NOT NULL DEFAULT '',
    species_raw TEXT NOT NULL DEFAULT '',
    length_cm   TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- TABLE: catches_scored
-- Computed scoring results — regenerated by rescore_all() whenever raw changes.
-- =============================================================================
CREATE TABLE IF NOT EXISTS catches_scored (
    id                BIGSERIAL PRIMARY KEY,
    season_id         TEXT NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
    comp_id           TEXT NOT NULL DEFAULT '',
    wp_no             TEXT NOT NULL DEFAULT '',
    species_raw       TEXT NOT NULL DEFAULT '',
    canonical_species TEXT NOT NULL DEFAULT '',
    length_cm         TEXT NOT NULL DEFAULT '',
    weight_kg         NUMERIC(10, 4) NOT NULL DEFAULT 0,
    edible            TEXT NOT NULL DEFAULT '',
    status            TEXT NOT NULL DEFAULT '',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- TABLE: team_assignments
-- Per-competition sub-team assignments (override the angler's default sub_team).
-- =============================================================================
CREATE TABLE IF NOT EXISTS team_assignments (
    comp_id     TEXT NOT NULL,
    season_id   TEXT NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
    wp_no       TEXT NOT NULL,
    sub_team    TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (comp_id, season_id, wp_no)
);

-- =============================================================================
-- TABLE: trophy_nominees
-- SDC / trophy nominee records per competition.
-- =============================================================================
CREATE TABLE IF NOT EXISTS trophy_nominees (
    trophy      TEXT NOT NULL,
    comp_id     TEXT NOT NULL,
    season_id   TEXT NOT NULL REFERENCES seasons(season_id) ON DELETE CASCADE,
    club        TEXT NOT NULL DEFAULT '',
    wp_no       TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (trophy, comp_id, season_id, wp_no)
);

-- =============================================================================
-- TABLE: theme_config
-- Singleton row (id = 1) storing the active colour theme as JSONB.
-- =============================================================================
CREATE TABLE IF NOT EXISTS theme_config (
    id          INTEGER PRIMARY KEY DEFAULT 1,
    theme_json  JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- Insert the default row so upsert always has something to update.
INSERT INTO theme_config (id, theme_json)
VALUES (1, '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- ROW LEVEL SECURITY
-- Disabled — Streamlit runs server-side with service_role key, no user sessions.
-- =============================================================================
ALTER TABLE seasons          DISABLE ROW LEVEL SECURITY;
ALTER TABLE anglers          DISABLE ROW LEVEL SECURITY;
ALTER TABLE competitions     DISABLE ROW LEVEL SECURITY;
ALTER TABLE catches_raw      DISABLE ROW LEVEL SECURITY;
ALTER TABLE catches_scored   DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE trophy_nominees  DISABLE ROW LEVEL SECURITY;
ALTER TABLE theme_config     DISABLE ROW LEVEL SECURITY;

-- =============================================================================
-- INDEXES — common query patterns
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_anglers_season      ON anglers (season_id);
CREATE INDEX IF NOT EXISTS idx_comps_season        ON competitions (season_id);
CREATE INDEX IF NOT EXISTS idx_catches_raw_season  ON catches_raw (season_id);
CREATE INDEX IF NOT EXISTS idx_catches_raw_comp    ON catches_raw (comp_id, season_id);
CREATE INDEX IF NOT EXISTS idx_catches_raw_wp      ON catches_raw (wp_no, season_id);
CREATE INDEX IF NOT EXISTS idx_scored_season       ON catches_scored (season_id);
CREATE INDEX IF NOT EXISTS idx_scored_comp         ON catches_scored (comp_id, season_id);
CREATE INDEX IF NOT EXISTS idx_scored_wp           ON catches_scored (wp_no, season_id);
CREATE INDEX IF NOT EXISTS idx_team_season         ON team_assignments (season_id);
CREATE INDEX IF NOT EXISTS idx_nominees_season     ON trophy_nominees (season_id);
